### ISSUE TITLE
Video cannot be loaded, please select another source

### ISSUE THREAD

**Issue by gallantcrusader** [goodtube4u/goodtube#17]
Why am I seeing this issue with every source? I was troubleshooting a bit so I did refresh a lot, so did it lock me out? I am so confused

**Comment by goodtube4u** [comment]
Hmm, well you definately haven't been locked out. Have you tried one of the 360p servers? They are generally more reliable.

New servers coming your way very soon! Hang tight.

Any further info on this issue? Device, browser, etc?

**Comment by gallantcrusader** [comment]
iOS 18b2, Orion

**Comment by goodtube4u** [comment]
A whole bunch of new servers have just been added (and they're really fast!).

Refresh youtube, you should see a popup prompting you to update up the tip right. Hit update, press update on the page that comes up, refresh Youtube.

Should be all good! Let me know if this fixes your issue :)
