### ISSUE TITLE
only 360p quality available 

### ISSUE THREAD

**Issue by Cocagy** [goodtube4u/goodtube#2]
only 360p quality available  , can you fix it ?

**Comment by goodtube4u** [comment]
Currently this plugin only supports 720p and 360p. If you're only seeing 360 then the video is likely originally only in 480p or lower.

I would like to enable all qualities in the near future, but there's some issues with Youtube recently injecting server side ads that are making it difficult unfortunately. Hang tight, when this is solved I'll add it.

In the meantime you can actually use the download button - which will give you any video or playlist in full HD quality (up to 8k).

Cheers.

**Comment by goodtube4u** [comment]
Actually, further on this - I realised that you are indeed correct. Youtube has turned off the 720p I was using, derp.

Good news is - it's pushed me to get DASH streams working. Meaning qualities in up to 1080p are now supported :)

Enjoy!
