### ISSUE TITLE
Fullcreen when double clicking seeking bar

### ISSUE THREAD

**Issue by tonehrk** [goodtube4u/goodtube#21]
I'm not sure if it's considered a bug. But it usually happens to me that by mistake I double click to seeking in the video and it turn to full screen. It's not really annoying, but I think it would be much better if that didn't happen.

Sorry if I don't write well in English

**Comment by goodtube4u** [comment]
Hello, very happy you're using this plugin and I hope it is working well for you.

Do not worry about your English, I understand what you are saying! :)

This is hard for me to change unfortunately, as this is part of the plugin I am using for the video player (called "Video JS").

I think it's too much trouble for how small it is at the moment. Try your best to click only once! Haha.

Peace and blessings my friend.
