### ISSUE TITLE
Play Speed options not working

### ISSUE THREAD

**Issue by qouqouroukou** [goodtube4u/goodtube#27]
When I need to change the speed of playing, all the options appear on screen when I tap the button  but when I select one of them eg 1.5x or whatever,  nothing happens. Only way  to speed up is by tap and hold on the video screen so  that 2x speed is enabled.

**Comment by goodtube4u** [comment]
Hey, thanks for reporting this issue! It has now been fixed and I have released an update. If you have any problems, please re-open this issue.

Thanks again! :)
