### ISSUE TITLE
Playlist skip issue

### ISSUE THREAD

**Issue by Nyrane** [goodtube4u/goodtube#28]
I've been using GoodTube for a while now and since yesterday everytime I put a playlist of any kind (mostly music) Youtube just skips the video every 2-4 seconds.
I'm using Chrome, everything is updated, history, cookies and caché clean as well, no other extension installed other than TamperMonkey and GoodTube, I'm on  PC Windows.
I have everything organized with Chrome, I would rather not start everything from 0 on another web browser.
I've seen another similar person with the same issue and I've tried everything you said to them, thanks for your time.
(PS: If the grammar is not perfect I apologize since it isn't my primary language).

Edit 1: I'm not sure if it matters but my current PC is used by two people including me, I have Firefox installed as well.

**Comment by goodtube4u** [comment]
Hey man, yep - I have also noticed this happening to me sometimes.

It is not a problem with your setup, I am also using Windows + Chrome.

Basically what is happening is Youtube sometimes detects this adblocker. I'm hiding their player and they seem to be cracking down on this a little bit lately.

However, I fixed this yesturday and it seems to be working perfectly for me. Have you updated to the latest version of GoodTube?

To check that simply go here:
https://github.com/goodtube4u/goodtube/raw/main/goodtube.user.js

Then hit update and refresh Youtube.

Let me know how you go :)

**Comment by goodtube4u** [comment]
If it does not work for you, please let me know - as there are other ways of hiding the youtube player that I am interested in trying.

**Comment by Nyrane** [comment]
It keeps happening, kinda annoying from YT to work harder on stopping adblocks rather than improving the experience of the user. 
Keep the good work and thanks for your efforts!

**Comment by goodtube4u** [comment]
Ok, so I've just pushed an update. Try the latest version and see how you go.

Fingers crossed it solves the issue, would be quite hard for Youtube to detect this new method :)

**Comment by goodtube4u** [comment]
Upon further testing, this is still happening intermittently. Hard to debug because it only happens sometimes.

Working on it, I listen to playlists all day so will fix asap - just working out what is causing it / testing. Will push a fix soon.

**Comment by goodtube4u** [comment]
Ok, big day but I think this is now fixed. If you can update and test on your end that would be great :)
