### ISSUE TITLE
Default Quality

### ISSUE THREAD

**Issue by Farqyee** [goodtube4u/goodtube#29]
Default quality keep changing on every video

**Comment by goodtube4u** [comment]
Can you provide some more information?

Basically the way this works is you click on "Select default quality" and then choose a default.
After that, for every video you play it will automatically select that quality (or the closest to it, if that quality is not available - for example, if you selected 1080p but then played a video with a max quality of 480p, it would select 480p).

If that is not how this is working, then please let me know the device, browser, etc.

Thanks

**Comment by Farqyee** [comment]
oh, just realize that "Select default quality" is a button, Sorry to bothering. thanks for explanation! great work!

**Comment by goodtube4u** [comment]
No problem my friend. Enjoy!
