### ISSUE TITLE
Clipping feature not working

### ISSUE THREAD

**Issue by Dasky14** [goodtube4u/goodtube#32]
It seems clipping is not supported yet? Is support for this feature planned in the future?

While I can click the clip button, the UI for naming and selecting the section for the clip is not visible on the right side of the page. Exiting the clipping mode is also impossible because the "do you want to discard the clip" prompt just quickly flashes on the screen and disappears.

**Comment by goodtube4u** [comment]
Hm, I was not even aware of this feature to be honest.

I've made an update to the code, so you should now be able to create clips without a problem.

Watching clips using GoodTube, however, will not work. It's too difficult to implement unfortunately.

Hopefully that helps, if your intention is to create and share clips at least.
