### ISSUE TITLE
Getting error popup when I load Youtube.

### ISSUE THREAD

**Issue by patchell13** [goodtube4u/goodtube#33]
"GoodTube could not be loaded! Please refresh the page to try again."

Tried closing browser, restarting etc.. still pops up. Followed instructions for desktop and used tapermonkey.

**Comment by patchell13** [comment]
If there is/are any additional information/logs I can provide, please let me know

**Comment by goodtube4u** [comment]
Hm, not sure why this would be happening on your end but my guess is you have another extension turned on that is blocking it. Can you try disabling your other extensions on Youtube, specifically adblockers?

Basically something is blocking the connection to this file:
https://raw.githubusercontent.com/goodtube4u/GoodTube/main/goodtube.min.js

The idea is, it gets the source from that file and loads it into the page. If that doesn't work you will see the "GoodTube could not be loaded! Please refresh the page to try again." error message.

**Comment by patchell13** [comment]
You were correct.. I had something blocking that URL on my end. Thank you!

**Comment by goodtube4u** [comment]
No worries, glad ya got it sorted and enjoy! :)
