### ISSUE TITLE
Does Not initiate video quality at "Auto"

### ISSUE THREAD

**Issue by pakapps** [goodtube4u/goodtube#34]
Every video starts with the highest quality resulting in buffering or high data consumption. Videos do not play with **"Auto"** quality initially or do not save/remember the video quality setting for future use. Please fix this.

**Comment by goodtube4u** [comment]
Actually there's functionality in this to do exactly that.

1. Click the quality menu
2. Click "select default quality"
3. Select "auto"

Now all videos will play with the quality "Auto" by default. You can also choose 360p, 720p, etc.

Feel free to re-open this if you have any problems.
