### ISSUE TITLE
How to watch youtube shorts 

### ISSUE THREAD

**Issue by jjfirst** [goodtube4u/goodtube#35]
I think you will change shorts to regular videos. but it's completely can't watch shorts anymore.
How can I watch shorts videos ? where is the setting ? Help me,please !!

**Comment by goodtube4u** [comment]
Sorry but I believe that shorts are bad for you, so with this plugin they are permenantly disabled.

**Comment by jjfirst** [comment]
I also don't like shorts-UI, but how i can watch shorts if my favorite youtuber release new shorts clip.

**Comment by goodtube4u** [comment]
Best way to do that would be to turn this off. It's not a feature I intend to add, sorry.
