### ISSUE TITLE
Not working on Edge

### ISSUE THREAD

**Issue by Colbalt01** [goodtube4u/goodtube#37]
![GoodTube Error](https://github.com/user-attachments/assets/00c76eb8-04ba-49f2-9e2a-8a8b7986856a)

For some reason, goodtube has stopped working for me on Edge. It was working a week or 2 ago. This error pops up on all pages. The error "This document requires 'TrustedHTML' assignment." occurs 9 times whenever a page loads in the console. I tried to update the script and my browser.

**Comment by goodtube4u** [comment]
Hey man, I actually just got the exact same thing happen to me in Chrome and pushed a fix about 30 minutes ago. It's got to do with some stupid browser update that just came out. Either way it should be fixed! :)

Can you try visiting this URL to update your script:
https://github.com/goodtube4u/goodtube/raw/main/goodtube.user.js

Let me know if you're still having issues after updating. I will 100% respond and help you to resolve this. It's a very urgent / important fix.

**Comment by goodtube4u** [comment]
Yeah, can confirm. Just tested the update in Edge and it's working. Closing the issue for now, feel free to re-open if you are still having problems.
