### ISSUE TITLE
Option to manage server list

### ISSUE THREAD

**Issue by dwroland** [goodtube4u/goodtube#39]
At the moment, to add or remove a server from the list we have to do a fork and make changes manually in the code

**Comment by goodtube4u** [comment]
This would be quite difficult I think. Is there a particular server you would like to add?

**Comment by dwroland** [comment]
You can store the list of custom values  as JSON.stringify() in the extension store
https://www.tampermonkey.net/documentation.php?locale=en#api:GM_setValue

I have local servers in the address pool 10.10.1.*. If I host goodtube on one of them, firefox mobile should also access that server.

**Comment by goodtube4u** [comment]
I've made some updates that will allow you to do this.

**To add a custom video server**
Visit youtube.com with the following GET params:
```
goodtube_customserver_0_name=My custom server
goodtube_customserver_0_type=2
goodtube_customserver_0_proxy=true
goodtube_customserver_0_url=https://mycustomserver.com
```

For example:
`https://youtube.com?goodtube_customserver_0_name=My custom server&goodtube_customserver_0_type=2&goodtube_customserver_0_proxy=true&goodtube_customserver_0_url=https://mycustomserver.co`

You can do this for up to 10 servers. Just change the '0' to '1', '2', '3' and so on. Eg
`goodtube_customserver_0_name` is the first server
`goodtube_customserver_1_name` is the second server

**To remove a custom video server**
Visit youtube.com with the following GET param:
`https://youtube.com?goodtube_customserver_0=false`

Hopefully that makes sense? Any questions hit me up.

**Comment by dwroland** [comment]
Hmm. It seems that it's not working. It just skips my server. No connection attempt in the logs on the server.
![Zrzut ekranu 2024-08-08 030036](https://github.com/user-attachments/assets/533b2f67-05cc-4522-8ae1-3f8397c13554)
![Zrzut ekranu 2024-08-08 030207](https://github.com/user-attachments/assets/71c4e47d-571e-4fcb-8efc-adc077df1c1a)

**Comment by goodtube4u** [comment]
Ah sorry there was a typo in the code. Give it a few minutes, refresh, should work. You don't need to update the setting or anything. Just leave it turned on and it should simply start working.

Can you check and let me know?

**Comment by dwroland** [comment]
Sure

**Comment by goodtube4u** [comment]
You sure? I just tried it and it's working for me.

My server is:
`http://127.0.0.1:3000`

So I used to test:
`https://www.youtube.com/?goodtube_customserver_1_name=Test%20server&goodtube_customserver_1_type=2&goodtube_customserver_1_proxy=true&goodtube_customserver_1_url=http://127.0.0.1:3000`

**Comment by dwroland** [comment]
https://www.youtube.com?goodtube_customserver_0_name=S1&goodtube_customserver_0_type=2&goodtube_customserver_0_proxy=true&goodtube_customserver_0_url=http://S1.lan

I have tried changing type but it still skipps.

**Comment by goodtube4u** [comment]
![image](https://github.com/user-attachments/assets/cdebbb97-7303-4912-9f97-b18036e7c488)

**Comment by goodtube4u** [comment]
I think maybe you've got the casing wrong.

Should it be:
`http://s1.lan/`

Instead of
`http://S1.lan/`

`https://www.youtube.com/?goodtube_customserver_0_name=S1&goodtube_customserver_0_type=2&goodtube_customserver_0_proxy=true&goodtube_customserver_0_url=http://s1.lan`

**Comment by dwroland** [comment]
`[GoodTube] Loading video data from s1... watch:1:52269
Zasady odsyłaczy: ignorowanie mniej ograniczonej zasady odsyłaczy „origin-when-cross-origin” w przypadku żądania między witrynami: http://s1.lan/api/v1/videos/3gL9kWD9XRo watch:1:5978
Zablokowano wczytywanie mieszanych treści aktywnych „http://s1.lan/api/v1/videos/3gL9kWD9XRo”`

And yeah, http://s1.lan/api/v1/videos/3gL9kWD9XRo is unreachable.

**Comment by goodtube4u** [comment]
I'd say that's because it's a mixed `http` type request.

You'll need to find a way to server over `https`. It let's you do this if you're using a local IP address like `127.0.0.1` but otherwise won't work (I don't have control over this, it's a built in piece of web security)

**Comment by dwroland** [comment]
Hmm. I have added port to server address. Now I can get answer from API but goodtube still refuse to connect.
`[GoodTube] Loading video data from s1... [watch:1:52269](https://www.youtube.com/watch?v=3gL9kWD9XRo%20line%207066%20%3E%20injectedScript)
Zasady odsyłaczy: ignorowanie mniej ograniczonej zasady odsyłaczy „origin-when-cross-origin” w przypadku żądania między witrynami: http://s1.lan:3000/api/v1/videos/3gL9kWD9XRo [watch:1:5978](https://www.youtube.com/watch?v=3gL9kWD9XRo)
Zablokowano wczytywanie mieszanych treści aktywnych „http://s1.lan:3000/api/v1/videos/3gL9kWD9XRo”
[watch:1:5978](https://www.youtube.com/watch?v=3gL9kWD9XRo)
Nieprawidłowy adres URI. Treść multimedialna „” nie została wczytana.`

![Zrzut ekranu 2024-08-08 033645](https://github.com/user-attachments/assets/cf3a0b2b-d5f0-4365-a2b9-33ebd156c858)
![Zrzut ekranu 2024-08-08 033742](https://github.com/user-attachments/assets/a223b033-1b20-445c-998e-43ec587d525e)

**Comment by dwroland** [comment]
Am I stupid or something? Port 443 should be open, but it's not...
![obraz](https://github.com/user-attachments/assets/c39e0176-2bbc-4295-8238-f4b0b149fb58)
![obraz](https://github.com/user-attachments/assets/28166ad6-3d00-4955-b46f-8588ea187173)

**Comment by goodtube4u** [comment]
Not sure to be honest. I'm not great with this side of things to be honest - and the invidious documentation is terrible haha. I wonder if that "state = closed" part of the log has any relevance? Just a guess.

**Comment by goodtube4u** [comment]
So I'm interested to know if you got this working in the end. If you work it out could you share the info? Might be nice to update the guide for other people that want to do something similar.

**Comment by dwroland** [comment]
I tried to do it quickly, but it is pain in the ass. Invidious docker container doesn't include nginx or any other service capable of reverse proxy, so I have to configure it myself. Maybe I will try it in the future.
For now, I simply made a workaround with the redirection using this script:
`// ==UserScript==
// @name         YT redirect
// @version      1.0
// @author       Greust
// @match        https://*.youtube.com/watch*
// @run-at       document-start
// ==/UserScript==
/* global $ */

function url_builder() {
    let params = {};
    let newURL = "http://"
        + "yt.lan:3000"
        + window.location.pathname
        + window.location.search
        ;
    return newURL;
}

(function () {
    'use strict';
    window.location.replace(url_builder());
})();`

**Comment by goodtube4u** [comment]
As in, you're just redirecting to your invidious instance and watching there?

**Comment by goodtube4u** [comment]
One thought I have had is that I might be able to unlock a lot of the restricted servers, and presumably request via normal http using GM_xmlhttpRequest:
https://www.tampermonkey.net/documentation.php?locale=en#api:GM_xmlhttpRequest

This is a built in tampermonkey thing (also supported by Violentmonkey, etc). It basically uses some trickery to allow you to do cross origin requests.

So what I would need to do is swap the fetch calls to use this instead.

That said, I'm not entirely sure it will work. The request could get the mainfest file, which contains all the parts of the video which are loaded into the player. But the parts of the video would be http and I'm unsure if that'll work from inside the player (same cross origin issue). Bit of work to test but on the cards one day...

**Comment by dwroland** [comment]
Yes, and so far it's working fine.
When I find some free time, I will try with this https://docs.linuxserver.io/general/swag/#docker-compose.
Thanks for the link to the chat.
