### ISSUE TITLE
Caption isn't working

### ISSUE THREAD

**Issue by Vechea** [goodtube4u/goodtube#4]
Tried to enabled caption to see if its working or not. It doesn't show any caption despite it saying it is running

**Comment by goodtube4u** [comment]
Yeah, I noticed that last night too actually. Some servers seem to be having issues returning subtitles - so I will put in a fallback to a working subtitle server today. Hang tight.

**Comment by goodtube4u** [comment]
This has now been fixed. Refresh youtube, you'll see a prompt to update up the top right. Update the script and should be all good! :)
