### ISSUE TITLE
Grey line in fullscreen mode

### ISSUE THREAD

**Issue by kurtthekunt** [goodtube4u/goodtube#41]
Using opera GX, goodtube creates a grey line in the bottom half of the screen when in fullscreen mode - and only in fullscreen mode

**Comment by goodtube4u** [comment]
Hey man, this is an issue with Opera by the looks of things. I've had a look around for information and there's a few things you can try.

1. In the top right next to the user icon is the settings icon, click on it and scroll down until you see RGX and click on both options so they are off.

2. If that doesn't work, try zooming in by 10%. Press ctrl and + (windows) or cmd and + (mac).

Hopefully that fixes your issue. If not, feel free to re-open this ticket.
