### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by highoncrack** [goodtube4u/goodtube#42]
Your shit doesn't work fix it

**Comment by goodtube4u** [comment]
Haha yes man, thank you for this insightful and polite bug report. Recently Youtube have thrown a real spoke in the works and messed up almost all alternative frontends (Invidious, Piped, etc) which this plugin uses.

They're working on a fix, when that is released is out of my control.

There is, however, hope. I am almost there with a new version of this, which doesn't rely on any video servers at all.

Currently it's working on desktop only, and downloads are yet to be supported. But if that suits your use case you can give it a try. Here's how ya do it:

1. Disable GoodTube in Tampermonkey.
2. Click this link: https://raw.githubusercontent.com/goodtube4u/GoodTube/main/beta/goodtube-embed.user.js
3. Hit install.

Hopefully that helps. Hopefully this calms your rage, highoncrack ;)
