### ISSUE TITLE
volume keeps reseting to 100% (chrome)

### ISSUE THREAD

**Issue by dramr** [goodtube4u/goodtube#44]
as the title said.  and the vid default quality is always 720p and not saving up whenever i choose 1080p or above.  it would be nice if the volume we choose to some extend will be save and not always go back to 100% and so as the vid quality. its always on 720p even if u change the settings of the vid quality.

sorry for my bad english

**Comment by goodtube4u** [comment]
Hi, no problem about the english - I understand.

The volume is remembered, so this should stay on whatever you choose.

You can select a default quality and this will be used for all videos. From the quality menu click on "Select default quality". Then you will see a popup, select 1080p (or anything you like) and it will use this for all videos :)

Please re-open this issue if you are still having problems.
