### ISSUE TITLE
Nothing Loads

### ISSUE THREAD

**Issue by tom-harvyy** [goodtube4u/goodtube#46]
![image](https://github.com/user-attachments/assets/f822eab4-7d3f-4589-bcd7-7e50f3879bc9)

It just gives me a spinning wheel when attempting to load content on Chrome Windows

**Comment by goodtube4u** [comment]
Yeah sorry, all the servers are down lately. Youtube managed to stop all instances of Invidious and Piped recently, and there's yet to be a fix released.

That said, there is a new alternative version of GoodTube that doesn't require any servers. Add this script to tampermonkey and you should be all good in chrome.
https://github.com/goodtube4u/goodtube/raw/refs/heads/main/beta/goodtube-embed.user.js

Currently desktop only and no downloads with this one, but it'll stop the ads ;)
