### ISSUE TITLE
F11/Fullscreen faint black bar on all videos (GoodTube V3.018)

### ISSUE THREAD

**Issue by Toasted32** [goodtube4u/goodtube#5]
Hey man, so far I'm enjoying GoodTube a whole bunch. I've come to find a visual bug that is hopefully something you can reproduce. Whenever I use the F11/F11 + Fullscreen function I get a faint black line across the screen that seems to follow the video. It isn't physical damage to my monitor either. I switch to a browser page at the end of my screen recording to verify it isn't system-wide or physical damage.

I'm stoked to see the journey of GT, and I'm sure this silly bug will be squashed soon enough!

Edited to add: I'm currently using Vivaldi V6.8.3381.46 (the latest release)

https://github.com/goodtube4u/goodtube/assets/137858741/24e22ee5-e908-40a7-a788-b3f1e39ad737

**Comment by goodtube4u** [comment]
Hey man,

Uh - not sure to be honest. It looks to be some sort of browser rendering issue, likely to do with the CSS.

I just downloaded Vivaldi and gave it a shot but couldn't make it happen on my end.

My best guess is that it might have to do with this line in the code (757):
padding-top: min(var(--ytd-watch-flexy-max-player-height), (calc(var(--ytd-watch-flexy-height-ratio) / var(--ytd-watch-flexy-width-ratio) * 100%))) !important;

Can you try changing that to
padding-top: 400px !important;

And let me know if that solves your issue? If it does, then I think I can get it fixed for ya :)

Cheers.

**Comment by Toasted32** [comment]
Hey,

So, that's a negative ghost rider. That silly black line is still there after changing the code to
`padding-top: 400px (var(--ytd-watch-flexy-max-player-height), (calc(var(--ytd-watch-flexy-height-ratio) / var(--ytd-watch-flexy-width-ratio) * 100%))) !important; `

I'm not too stressed about it, if you can't reproduce it, then I'm sure it's something I've done. I'll go ahead and fresh install vivaldi to see if that fixes it as well

**Comment by goodtube4u** [comment]
Yeah, just replace the entire line with:
padding-top: 400px !important;

You don't need all the rest of it :)

**Comment by Toasted32** [comment]
Ah I see, yeah the replacement code didn't work. It's all good, I can live with it. You can close out/resolve this issue tbh

**Comment by SpiritAxolotl** [comment]
you should try revanced instead. goodtube uses it in the backend anyways so you might as well cut out the middleman
https://revanced.net/

**Comment by Toasted32** [comment]
> you should try revanced instead. goodtube uses it in the backend anyways so you might as well cut out the middleman https://revanced.net/ or https://cobalt.tools for downloading videos directly, which goodtube _also_ freeboots off of

Yeah, I'm using Windows 10. I'm not about to emulate to use revanced, but I appreciate the suggestion. I did, however, use cobalt well before this whole fiasco went down

**Comment by goodtube4u** [comment]
Yeah ^ that guy is from cobalt. They're mad because we use them for downloads.

Quite the bunch of angry dudes it seems.

Also this doesn't use ReVanced - but either way, please just ignore these bozos haha.

I will have a guess at fixing your issue in the next release man. Hang tight!
