### ISSUE TITLE
GitHub is for source code, not for obfuscated (claims to be minified) scripts for "performance reasons"

### ISSUE THREAD

**Issue by ihatespawn** [goodtube4u/goodtube#8]
The main script is now **obfuscated** and because of that basically no one can contribute or ever read the code.
```
// This code has been minified for performance reasons.
// If you're interested in the source code, send me a message! :)
```
If it's for performance reasons, MAKE ANOTHER SCRIPT WITH THE FULL SOURCE CODE
Also, I un"minified" this code and it's obfuscated not minified.

**Comment by lostdusty** [comment]
absolute cinema
